### ISSUE TITLE
Data update for 10.0

### ISSUE THREAD

**Issue by fang2hou** [MMOSimca/LibObjectiveProgress-1.0#1]
Hi, Simca, I am a user of this addon since Legion.

Do you have plan to add data of Dragonflight?

I am very glad to help you maintain the weight data if there is a simple introduction of data mining.
I tried to find the clue in `Criteria.db2 / CriteriaTree.db2 / Scenario.db2 / ScenarioStep.db2 / Map.db2` which are mentioned in your code, but I have no clue to calculate the weight data (especially the weight data for quests). 😢

Thank you for the awesome useful addon.

**Comment by MMOSimca** [comment]
Hey; I didn't see your issue until now. I'm still maintaining the addon, but it's definitely a lot of work for each version, even with the level of automation I have in my tools for generating the data now.

This is because data only exists for quests players have seen. If a World Quest has never popped up before when I do the update, it won't be included. So to be truly comprehensive, I'd need to do many different small data updates per version. I currently don't have an expedient way to do this (though it is something I'm working on).
